# Generated by Django 3.1.2 on 2020-10-07 17:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=8),
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), default=[], size=8),
        ),
        migrations.AddField(
            model_name='question',
            name='times_answered',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='times_correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='body',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
