# Generated by Django 3.1.3 on 2020-11-08 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_auto_20201107_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='parlayuser',
            name='class_code',
            field=models.CharField(default='', max_length=500),
        ),
    ]
