# Generated by Django 3.1.3 on 2020-11-12 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_result_award_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='assigned_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.class'),
        ),
    ]
