# Generated by Django 3.1.2 on 2020-10-19 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='result',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.level'),
        ),
    ]
