# Generated by Django 3.1.3 on 2020-11-12 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_level_assigned_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='assigned_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.class'),
        ),
    ]
