# Generated by Django 3.1.2 on 2020-11-03 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0009_auto_20201102_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='choice',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterIndexTogether(
            name='response',
            index_together={('player', 'question', 'choice')},
        ),
    ]
