# Generated by Django 3.1.2 on 2020-11-03 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0010_auto_20201103_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='accuracy',
            field=models.FloatField(default=100.0),
        ),
    ]
