image: python
stages:
  - test
  - deploy

run_django_tests:
  stage: test
  tags:
    - db-connected
  script: 
    - pip install pipenv
    - pipenv install
    - pipenv run python3 manage.py test

deploy_to_stage:
  stage: deploy
  environment:
    name: staging
  script:
    - brew install awsebcli
    - eb deploy parlay-island-server-dev
  only:
    - master

deploy_to_prod:
  stage: deploy
  environment:
    name: prod
  when: manual
  script:
    - brew install awsebcli
    - eb deploy parlay-island-server-prod
